apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:webhook-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-dnspod.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Once we no longer have to support Kubernetes versions lower than 1.17, we
# can remove this custom defined Role in favour of the system-provisioned
# extension-apiserver-authentication-reader Role resource in kube-system.
# See https://github.com/kubernetes/kubernetes/issues/86359 for more details.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:webhook-authentication-reader
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:auth-delegator
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-dnspod.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups:
      - {{ .Values.groupName }}
    resources:
      - '*'
    verbs:
      - 'create'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:domain-solver
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ if empty .Values.certManager.namespace }}"cert-manager"{{ else }}{{ .Values.certManager.serviceAccountName }}{{ end }}
    namespace: {{ if empty .Values.certManager.namespace }}{{ .Release.Namespace }}{{ else }}{{ .Values.certManager.namespace }}{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:secret-reader
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  resourceNames:
  - {{ include "cert-manager-webhook-dnspod.fullname" . }}-secret
  verbs:
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:secret-reader
  labels:
    app: {{ include "cert-manager-webhook-dnspod.name" . }}
    chart: {{ include "cert-manager-webhook-dnspod.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cert-manager-webhook-dnspod.fullname" . }}:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "cert-manager-webhook-dnspod.fullname" . }}
